apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-goat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/0xZainRaza/Kubernetes-Security-Hardening
    targetRevision: main
    path: kubernetes-goat
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  info:
    - name: description
      value: Kubernetes Goat vulnerable scenarios